### ISSUE TITLE
Launching server using command pls failed (vscode)

### ISSUE THREAD

**Issue by please-fill-out-this-field** [FractalBoy/perl-language-server#107] opened 2022-06-19 10:52 UTC
Whenever I try to open some `.pl` or `.pm` in vscode I get an error message
```
Couldn't start client Perl Language Server (PLS)
```
followed by a notification
```
A request has failed. See the output for more information.

Source: Perl Language Server (PLS) (Extension) [Go to output]
```

So I'm clicking that `[Go to output]` thing and that's what I'm getting in the OUTPUT tab:
```
[Error - 2:15:58 PM] Starting client failed
Launching server using command pls failed.
```
Running `pls` from bash works fine though.

All other Perl-related extensions that can possibly interfere with this one are disabled - the only one left enabled is the default vscode extension for Perl files.

`Perl::Critic` and `Perl::Tidy` are installed and up-to-date:
```
$ cpanm Perl::{Critic,Tidy}
Perl::Critic is up to date. (1.140)
Perl::Tidy is up to date. (20220613)
```
Both `~/.perlcriticrc` and `~/.perltidyrc` exist in the filesystem.

Code OSS v1.67.2 x Perl 5.34.0 (perlbrew) x PLS 0.899 x fractalboy.pls v0.0.14 (installed manually from `.vsix`) on Linux.

**Comment by FractalBoy** [comment] 2022-06-19 11:12
Please try changing the pls path to the full path to pls.

**Comment by please-fill-out-this-field** [comment] 2022-06-19 11:18
> Please try changing the pls path to the full path to pls.

Already.

That worked, but isn't it better to rely on `env` for locating executables?

**Comment by FractalBoy** [comment] 2022-06-19 12:44
It does, but just because your environment is correct in your terminal does not mean it's correct in VSCode.

**Comment by FractalBoy** [comment] 2022-06-22 15:50
Closing as this is not a bug with pls but a UX issue with VSCode.

**Closed** 2022-06-22 15:50 UTC
